language: generic

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-elisp/ppa'
    packages:
      - emacs
      - emacs-snapshot

env:
  matrix:
    - EMACS=emacs
    - EMACS=emacs-snapshot

matrix:
   allow_failures:
     # emacs-snapshot (daily snapshot) is not yet stable version
     - env: EMACS=emacs-snapshot

before_install:
  - $EMACS --version

install:
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=${PATH}:${HOME}/.cask/bin
  - cask install

script:
  - make compile
  - make test
